# Generated by Django 3.1.1 on 2020-11-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='port_website',
            field=models.URLField(default='https://github.com/WillLantz?tab=repositories', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Comment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
    ]
