# Generated by Django 3.1.1 on 2020-11-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0003_auto_20201128_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='port_website',
            field=models.URLField(default='https://github.com/WillLantz', max_length=500),
        ),
    ]
